import { ToastContainer } from "react-toastify";
import { Inter } from "next/font/google";
import "@rainbow-me/rainbowkit/styles.css";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { Context } from "./context";
import { ThemeProvider } from "@/theme/ThemeProvider";
import { ToastProvider } from "@/hooks/ToastProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "WOW Bridge",
  description: "Generated by Evola Labs",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer />
        <ToastProvider>
          <ThemeProvider>
            <Context>
              {children}
            </Context>
          </ThemeProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
